Unit tests
SuperDARN/pyDARNio pull request #9
Opened 2020-10-02 13:28 UTC by aburrell

Updated unit tests, partially addressing issue #8 

- Test files are currently missing, but a `skipIf` command is in place
- You can run the tests from the pyDARNio directory using: `python3 -m unittest discover`

The Borealis tests are currently failing.  It looks like the testing data in the borealis_*_data_sets.py files are not up to snuff.  @mardet987 I would appreciate you taking a look at this.

2020-10-09 14:20 UTC, mts299 requested changes
@aburrell I am noticing a lot of changes with no comments, and ones that don't match the previous code. If these changes are on preference then actual reason. I would prefer them to go back to normal. 

Also, pyDARNio will break any install where PyPI is uploaded with pydarnio. PLEASE if you are going to make these decisions then make an issue to discuss.

2020-10-09 14:20 UTC, mts299 commented on pydarnio/borealis/base_format.py
> +from pyDARNio import borealis_exceptions
Actually its still `pydarnio`, PEP8 requires no capitals in a library name and I would like to stick to it as that is how I uploaded it to pypi

2020-10-09 14:20 UTC, mts299 commented on pydarnio/dmap/dmap.py
> +from pyDARNio import dmap_exceptions
Again why? This follows PEP8 import style https://www.python.org/dev/peps/pep-0008/#imports

2020-10-09 14:31 UTC, aburrell commented on pydarnio/borealis/base_format.py
> +from pyDARNio import borealis_exceptions
I changed this because it didn't work otherwise.  I would also rather not have capitalization in the module name, but not using it causes failure on my system.  I believe this would be solved by changing the directories to `pydarnio`, but that's a big change that would need discussion.

2020-10-09 14:35 UTC, aburrell commented on pydarnio/borealis/borealis_site.py
> +        self._record_names = sorted([bkey for bkey in borealis_records.keys()])
The old style of casting keys as a list frequently fails, so I changed it to something that wasn't failing locally.

2020-10-09 14:36 UTC, aburrell commented on pydarnio/dmap/dmap.py
> +from pyDARNio import dmap_exceptions
The other imports were removed because they aren't used here anymore.

2020-10-09 14:37 UTC, mts299 commented on pydarnio/borealis/base_format.py
> +from pyDARNio import borealis_exceptions
I don't know what you are using, did you install your code? Maybe you should make an issue instead of changing code that will break others' code. 

I have no problem with pydarnio.

2020-10-09 14:38 UTC, aburrell commented
Right.  The changes are to remove the duplication and make the tests easier to maintain.  It's a big overhaul, so it's going to look different.  However, it addresses most of the "TODO" in the unit tests.  I would be happy to go over the new unit testing structure with the pyDARNio crew if people are interested.

WRT comments, the tests are the same tests as before, with some additional coverage and smart skipping.  All of the tests have descriptive docstrings.  I haven't put descriptive docstrings in the test classes, but can add those if the developers would like them.

2020-10-09 14:41 UTC, mts299 commented on pydarnio/borealis/base_format.py
> +from pyDARNio import borealis_exceptions
Also, the main directory is `pydarnio`
```
build  dist  docs  LICENSE  mkdocs.yml  pydarnio  pydarnio.egg-info  README.md  setup.py  tests
```

2020-10-09 14:42 UTC, aburrell commented on pydarnio/borealis/base_format.py
> +from pyDARNio import borealis_exceptions
> I believe this would be solved by changing the directories to pydarnio, but that's a big change that would need discussion.

2020-10-09 14:47 UTC, mts299 commented on pydarnio/dmap/dmap.py
> +from pyDARNio import dmap_exceptions
They are listed below nothing has been removed?

2020-10-09 14:47 UTC, mts299 commented on tests/unit/file_utils.py
> +
I believe this filename needs test_<name> before it.

2020-10-09 14:47 UTC, mts299 commented on tests/unit/file_utils.py
> +from glob import glob
I try to keep from out of direct imports. Something PEP8 suggests ... I think.

2020-10-09 14:47 UTC, mts299 commented on tests/unit/test_dmap.py
> +    def test_bad_array_to_byes(self):
``` suggestion
    def test_bad_array_to_bytes(self):
```

2020-10-09 14:47 UTC, mts299 commented on tests/unit/test_dmap.py
> -    def test_String_array(self):
Why are you removing these tests?

2020-10-09 14:55 UTC, aburrell commented on pydarnio/borealis/base_format.py
> +from pyDARNio import borealis_exceptions
The comment I liked was helpful, and this issue was addressed in the most recent commit.

2020-10-09 14:58 UTC, aburrell commented on tests/unit/file_utils.py
> +from glob import glob
Really?  I don't mind changing, but have never heard that before.

2020-10-09 15:18 UTC, mts299 commented
Sorry, @aburrell there is a lot of changes here and not just unit tests which don't make sense to me or why you changed them. 
 
You apparently fixed bugs, wrote a new test or file getter, and edited a lot on the unit tests and this is too much to review in one PR. 

The scope is a bit wide and I probably asking "why?" a lot. Somethings like `import pyDARNio` vs. `import pydarnio` confuses me and its apparently a bug for only you. But I know nothing of the details. 

I would recommend making multiple branches that reflect each portion of changes and updates. Also, if you pick things based on preferences then make a PR on that, some people like their code to reflect their style so changing it might be a bit triggering like myself. 

Also shouldn't the file getting test thing to be part of when we make a test data set? 

Otherwise, not sure I can review this anytime soon.

2020-10-09 15:24 UTC, mts299 commented
Thank you for all this code and for looking over everything! I would just like to have more focus on what is going on in many of the changes. Hopefully, separate branches are not too much of a pain.

2020-10-09 15:48 UTC, aburrell commented
You may or may not be surprised to know that this already a sub-branch of this project.  It's a big restructure, that I spent a fair bit of time scoping to ensure that all the original work was kept while making it easier to maintain and run in the future.  

This PR could be broken into DMap/SuperDARN changes and Borealis changes, but I don't know how to do that (my GitFoo is fairly basic).

What I could do to help reviewers and future development is create a document describing the new structure, how it applies to the old structure, and what's useful about the new structure.  I could see from the tone of your comments that "[...] changing it might be a bit triggering like myself." was in play, but I did not change anything without thinking through best practices for unit tests and considering multiple alternatives.  None of the changes are based on my stylistic preferences.  Hopefully the document will help the current and future developers with unit and integration tests.

Just a note, that I am currently on 0% SuperDARN time, so it will likely be a while before I get the testing structure file posted to the wiki or another suitable location.  When I do I'll link it here.

2020-10-09 16:00 UTC, mts299 commented
sub-branch? Should this be a draft PR then or merging not to `develop`? 

Well make branches and copy the changes over that fit the scope. Possible branches:
- [ ] import pyDARNio 
- [ ] preferences or updates to DMap (explanations)
- [ ] preferences or updates to SuperDARN 
- [ ] preferences or updates to Borealis
- [ ] updates to unit test structure 
- [ ] preferences or changes to current unit tests 
- [ ] file reading for unit tests 

If you did find any other BUGS then make those a PR and issue. 
The new structure of pydarnio or unit tests? Why are we changing so much? 

Documentation would help but separate PRs and issues would also help. 
You haven't tested the new structure?

2020-10-09 16:11 UTC, mts299 commented on pydarnio/dmap/dmap.py
> +        array_data_bytes = array_value.tobytes()
why this?

2020-10-09 16:11 UTC, mts299 commented on pydarnio/dmap/dmap.py
> +from pyDARNio import dmap2dict, dict2dmap
``` suggestion 
from pydarnio import dmap_exceptions, DmapArray, DmapScalar, dmap2dict, dict2dmap
```

2020-10-09 16:11 UTC, mts299 commented on pydarnio/exceptions/dmap_exceptions.py
> +        self.message = "Error: {} is empty or" \
why space?

2020-10-09 16:11 UTC, mts299 commented on tests/unit/borealis_utils.py
> +# Copyright (C) 2020 NRL
What is this test file for?

2020-10-09 16:11 UTC, mts299 commented on tests/unit/borealis_utils.py
> +    def setUp(self):
docstring?

2020-10-09 16:11 UTC, mts299 commented on tests/unit/borealis_utils.py
> +    def tearDown(self):
doc string

2020-10-09 16:11 UTC, mts299 commented on tests/unit/borealis_utils.py
> +def get_borealis_type(file_type, file_struct, version):
``` suggestion
def get_borealis_type(file_type: str, file_struct: str, version: int):
```

2020-10-09 16:11 UTC, mts299 commented on tests/unit/borealis_utils.py
> +    def load_file_record(self, file_type=''):
``` suggestion
    def load_file_record(self, file_type: str = ''):
```

2020-10-09 16:11 UTC, mts299 commented on tests/unit/borealis_utils.py
> +    def load_temp_file(self, file_type=''):
``` suggestion
    def load_temp_file(self, file_type=''):
```

2020-10-09 16:11 UTC, mts299 commented on tests/unit/file_utils.py
> +from glob import glob
just a preference.

2020-10-09 16:11 UTC, mts299 commented on tests/unit/file_utils.py
> +
Can you add typing in all your function calls to be consistent?

2020-10-09 16:17 UTC, aburrell commented on pydarnio/dmap/dmap.py
> +from pyDARNio import dmap2dict, dict2dmap
Your old way fails flake8

2020-10-09 16:21 UTC, aburrell commented on pydarnio/dmap/dmap.py
> +        array_data_bytes = array_value.tobytes()
`tostring` has been deprecated.

2020-10-09 16:21 UTC, aburrell commented on pydarnio/dmap/dmap.py
> +from pyDARNio import dmap2dict, dict2dmap
In the last commit I combined the bottom two imports for you.

2020-10-09 16:22 UTC, aburrell commented on tests/unit/borealis_utils.py
> +    def load_temp_file(self, file_type=''):
Is there a change here?  It looks identical to me.

2020-10-09 16:23 UTC, aburrell commented on tests/unit/file_utils.py
> +
Yes, I can do that.

2020-10-09 16:26 UTC, aburrell commented on pydarnio/exceptions/dmap_exceptions.py
> +        self.message = "Error: {} is empty or" \
Flake8 prefers spaces before all operators.

2020-10-09 16:38 UTC, aburrell commented
>sub-branch? Should this be a draft PR then or merging not to develop?

No, the upcoming changes will be a draft once they're ready

> Well make branches and copy the changes over that fit the scope. Possible branches:
>  import pyDARNio
Already taken care of in https://github.com/SuperDARN/pyDARNio/pull/9/commits/ef9f62c0c93c317493adc9eecdb3da09b6dcd6ab and 39cc7fd

> preferences or updates to DMap (explanations)
> preferences or updates to SuperDARN
> preferences or updates to Borealis

They are a very small number of changes to make the code flake8 compliant and robust across python 3 versions.  Doesn't seem worth the effort.

> updates to unit test structure
> preferences or changes to current unit tests
> file reading for unit tests

These are all linked together

> If you did find any other BUGS then make those a PR and issue.
Fair point; it's the one pydarn import.

> The new structure of pydarnio or unit tests? Why are we changing so much?  
I've addressed this multiple times in comments and told you I will supply more detail in documentation.

> Documentation would help but separate PRs and issues would also help.
I'll do what I can given the time and resources available to me.

> You haven't tested the new structure?
Of course I've tested the new structure.  As stated in my top comment when creating this PR everything passes locally but Borealis, which was failing beforehand anyhow.  As I said in the previous comment, separating DMap/SuperDARN and Borealis would probably be helpful here.  But, as I said in the previous comment, I don't know how to do that.

Given your review thus far what I need from you is help learning how to separate this PR into separate PRs.

I will also address the important style issues you identified (e.g.  missing docstrings and type hinting), but will not be working on this PR or commenting on it again for at least a week.

2020-10-16 16:12 UTC, mardet987 commented
Hey @aburrell I tried testing using 
`python3 -m unittest discover`
Like you suggested but had a couple of issues. 

If I run from the pydarnio package's root dir as suggested, I get this error, I guess it is not finding the module to import, similar with the file_utils for test_dmap and test_superdarn:

> ======================================================================
ERROR: tests.unit.test_borealis (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.unit.test_borealis
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "/Users/Marci/code/pydarnio/tests/unit/test_borealis.py", line 23, in <module>
    import borealis_utils
ModuleNotFoundError: No module named 'borealis_utils'

I then tried the same thing from just within the test/unit subdirectory so the above wasn't an issue. I saw some mention of this issue in the discussion above.

>======================================================================
ERROR: test_dmap (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_dmap
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "/Users/Marci/code/pydarnio/tests/unit/test_dmap.py", line 11, in <module>
    import file_utils
  File "/Users/Marci/code/pydarnio/tests/unit/file_utils.py", line 14, in <module>
    import dmap_data_sets
  File "/Users/Marci/code/pydarnio/tests/unit/dmap_data_sets.py", line 6, in <module>
    from pyDARNio import DmapArray, DmapScalar
ModuleNotFoundError: No module named 'pyDARNio'

The capitalization is messing up the import, I tried 'import pyDARNio' in the interpreter and got the error as well. Is there a plan to fix this? I can work around these to get to the Borealis testing issues for now.

2020-10-16 16:17 UTC, mardet987 commented
Sorry - I see I missed an update. Ignore that last bit!

2020-10-16 16:48 UTC, mardet987 commented
I just noticed that you reverted some imports in other files so I reverted them where I was having more issues.

2020-10-16 21:24 UTC, mardet987 commented
Update: still working on this and the read unittests

2020-10-19 22:22 UTC, mardet987 commented on tests/unit/file_utils.py
> +    files = glob("ls {:s}".format(os.path.join(test_dir, test_file_type, "*")))
does having the 'ls' in there for this glob work for the other tests? I could not get this to work for me for the Borealis tests. I would suggest the following but want to be sure it doesn't affect the other tests. 
```suggestion
    files = glob("{:s}".format(os.path.join(test_dir, test_file_type, "*")))
```

2020-10-30 23:23 UTC, mardet987 commented
Ok I completed the read tests now without issue!

@mts299 I remember discussing putting test files somewhere, where could I put the testdir that I used for this? 

Also, I was wondering if it is possible for us to discuss the pydarnio_logger.error() in the exception initiation. It prints the error to screen which can be misleading if the error then doesn't get raised (for example, in a try/except which I use in the BorealisRead and BorealisWrite classes to determine the version and file structure). The one that I've found has been an issue is line 344 in borealis_exceptions.py which prints the Structure error even though it is often caught and the correct structure subsequently found.

2020-11-02 17:44 UTC, mts299 requested changes
I think this might be my last review before approving it. Some things I am still what is going on.

2020-11-02 17:44 UTC, mts299 commented on tests/unit/file_utils.py
> +    def setUp(self):
Can you add docstring on setUP and tearDown on what they are doing?

2020-11-02 17:44 UTC, mts299 commented on tests/unit/file_utils.py
> +    def setUp(self):
Docstrinngs here as well and for other missing ones on test classes

2020-11-02 17:44 UTC, mts299 commented on tests/unit/test_conversions.py
>  import pydarnio
```suggestion
```

2020-11-02 17:44 UTC, mts299 commented on tests/unit/test_dmap.py
> +# Author: Marina Schmidt, Angeline Burrell
```suggestion
# Author: Marina Schmidt
# Modification:
# 2020-11 Angeline Burrell converted pydarnio tests to pytests and updated that code to have teardowns and setups. 
```

Actually, you would need to change the overall functionality and meaning to add your name as an Author.

2020-11-02 17:44 UTC, mts299 commented on tests/unit/test_dmap.py
> -    def test_dmap_read_stream(self):
Why are you removing all these tests?

2020-11-02 17:46 UTC, mts299 commented
@mardet987 @aburrell where would you like the test files? 

Ther `pydarn.logger.error()` should not activate unless it's set on? Did you do that or wise this may be a bug

2020-11-03 19:54 UTC, mardet987 commented on pydarnio/exceptions/borealis_exceptions.py
>          pyDARNio_logger.error(self.message)
@mts299 this is the line I'm talking about.

I didn't change any pydarnio_logger settings, but this wrote to stdout even though the exception was later caught. 

Did we discuss FRDR or CEDAR for a directory of test files?

2020-11-03 20:59 UTC, mts299 commented on pydarnio/exceptions/borealis_exceptions.py
>          pyDARNio_logger.error(self.message)
huh... might need to look into that? 

Yes looks like you found it on the DAWG repo?

2020-11-03 22:11 UTC, mardet987 commented on pydarnio/exceptions/borealis_exceptions.py
>          pyDARNio_logger.error(self.message)
is this call supposed to write to stdout?

Yes I found the DAWG issue, I can upload files wherever but I don't have experience with FRDR. If that's the choice, please point me to the location where I should upload!

2025-10-01 21:07 UTC, carleyjmartin commented
Closing for now as very stale but will add testing to WG meeting agenda.

2025-10-01 21:07 UTC, closed without merging